wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.13.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc_step
      5: 1
      6:
      - 1
    - 1: val_acc_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: gradients/linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: test_acc_step
      5: 1
      6:
      - 1
    - 1: test_acc_epoch
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_1hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_2hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_3hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_4hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_5hidden\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6bn\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/graph_6hidden\.weight.bins
      5: 1
      6:
      - 1
    python_version: 3.8.12
    start_time: 1644936320
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      3:
      - 17
      4: 3.8.12
      5: 0.12.9
      6: 4.13.0
      8:
      - 5
